### ISSUE TITLE
Find person by Email Address

### ISSUE THREAD

**Issue by trevski** [kekekeks/pipedrive-net#11]
Not setup my dev envionrment to use GIT here is the snipped I added to get this working

**Comment by trevski** [comment]
public Task<TPerson> Find(string email)
        {
            return _client.Get<TPerson>("persons/find?term=" + email + "&start=0&search_by_email=1");
        }

**Comment by kekekeks** [comment]
You need to call `Uri.EscapeDataString` on email before concatenating

**Comment by trevski** [comment]
Thanks

  public Task<TPerson> Find(string email)
        {
            return _client.Get<TPerson>("persons/find?term=" + Uri.EscapeDataString(email) + "&start=0&search_by_email=1");
        }

**Comment by trevski** [comment]
Find on the API does not seem to return a full person record, i am getting

Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'PipedriveNet.Dto.PersonDto' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path 'data', line 1, position 24.

**Comment by kekekeks** [comment]
You need to use `List<Person>` then

**Comment by trevski** [comment]
Yes I tried that already. this is the Json returned 
![screenshot](https://cloud.githubusercontent.com/assets/284619/16464331/9d185278-3e31-11e6-9e24-1de39c1403b3.png)

**Comment by trevski** [comment]
When using  List<TPerson> I am getting

Error converting value "albert@clunknasty.com" to type 'System.Collections.Generic.List`1[PipedriveNet.Dto.PipedriveStringListItemDto]'. Path 'data[0].email', line 1, position 90.

**Comment by trevski** [comment]
The problem is that the Find does not return a person.

I have added a new DTO for PersonFind and gotten it working locally, if you make me a team member I will merge it.

**Comment by trevski** [comment]
This is now included in latest pull request from Eonic
