### ISSUE TITLE
Getting hung on deals endpoint

### ISSUE THREAD

**Issue by tqrecords** [kekekeks/pipedrive-net#9]
For some reason, the api doesn't seem to return any data when I added it to my main project via the dll. Using this code:

var client = new PipedriveClient(token); 
var deals = client.Deals.All.Result;

It gets hung on the second line. I use the same code in the Sandbox project from the solution and it brings back the first 100 results.

**Comment by kekekeks** [comment]
Are you using it from WPF or winforms? Because you can't reliably use Task.Result from UI thread. Use `await` instead.

More info: https://download.microsoft.com/download/5/B/9/5B924336-AA5D-4903-95A0-56C6336E32C9/TAP.docx

**Comment by tqrecords** [comment]
Thanks, that helped.

var deals = await client.Deals.All;

**Comment by trevski** [comment]
I am struggling getting this working in my solution I have the same issue I suspect. I put in await and i get an error saying await can only be used in an async method. can you spot my problem

 public void saveApplicantPD(ref FCVAPI.Models.Applicant applicant)
        {
            try
            {
                string myKey = goConfig["PipedriveApiKey"];

                PipedriveNet.PipedriveClient pdClient = new PipedriveNet.PipedriveClient(myKey);

                PipedriveNet.Dto.StageDto firstStage = await pdClient.Stages.All.Result[1];

                //Find the person
                PipedriveNet.Dto.PersonDto person = pdClient.Persons.Find(applicant.Email).Result;

                if (person == null) {
                    //Create the person
                    person = pdClient.Persons.Create(applicant.FirstName + "" + applicant.LastName, applicant.Email, applicant.Telephone).Result;
                }
                else
                {
                    //Update the person
                    person = pdClient.Persons.Update(person.Id,applicant.FirstName + "" + applicant.LastName, applicant.Email, applicant.Telephone).Result;
                }
                //Create the deal
                pdClient.Deals.Create("CV Review", "0", "GBP", person.Id, 1);


            }
            catch (Exception ex)
            {
                if (OnError != null)
                {
                    OnError(this, new Eonic.Tools.Errors.ErrorEventArgs(mcModuleName, "SaveApplicant", ex, ""));
                }
            }
        }

**Comment by kekekeks** [comment]
Don't use `Task.Result` or `Task.Wait` from your UI thread. Use `async`/`await` instead.

See more info there:  https://www.microsoft.com/en-us/download/details.aspx?id=19957

**Comment by kekekeks** [comment]
https://msdn.microsoft.com/en-us/library/mt674882.aspx

**Comment by trevski** [comment]
Can you give me an example of how that would look in this context ? I am not at all familiar with async programming

**Comment by trevski** [comment]
is this closer, still giving me errors?

 Task<List<PipedriveNet.Dto.StageDto>> TStages = pdClient.Stages.All.Result;
 List<PipedriveNet.Dto.StageDto> Stage = await TStages;
 PipedriveNet.Dto.StageDto firstStage = Stage[1];

**Comment by kekekeks** [comment]
Something like that:

```csharp
async void button1_Click(object sender, EventArgs args)
{
     button1.Enabled = false;
     try
     {
             PipedriveNet.PipedriveClient pdClient = new PipedriveNet.PipedriveClient(myKey);

            PipedriveNet.Dto.StageDto firstStage = (await pdClient.Stages.All)[1];

            //Find the person
            PipedriveNet.Dto.PersonDto person = await pdClient.Persons.Find(applicant.Email);

            if (person == null) {
                //Create the person
                person = await pdClient.Persons.Create(applicant.FirstName + "" + applicant.LastName, applicant.Email, applicant.Telephone);
            }
            else
            {
                //Update the person
                person = await pdClient.Persons.Update(person.Id,applicant.FirstName + "" + applicant.LastName, applicant.Email, applicant.Telephone);
            }
            //Create the deal
            pdClient.Deals.Create("CV Review", "0", "GBP", person.Id, 1);

     }
        catch (Exception ex)
        {
            if (OnError != null)
            {
                OnError(this, new Eonic.Tools.Errors.ErrorEventArgs(mcModuleName, "SaveApplicant", ex, ""));
            }
        }
     finally
     {
          button1.Enabled = true;
     }
}
```

But you'd better to actually learn how async/await works, you'll get weird bugs otherwise

**Comment by trevski** [comment]
Thanks I needed to make my whole sub async, will spend more time trying to understand this, thanks.
